### ISSUE TITLE
[request] Deploy 1.0.3 / 1.0.x* to Steam Workshop

### ISSUE THREAD

**Issue by BeauBouchard** [shadowhen89/EquipBestItem#3]
After merging https://github.com/shadowhen/EquipBestItem/pull/2  the EquipBestItem is pretty solid for the current versions. Could you please publish the version that is on Nexus to Steam Workshop? 

Also thank you for the module, its the top one for a lot of people.

**Comment by shadowhen** [comment]
I have considered publishing EquipBestItem to the Steam Workshop, but I don't have a lot of free time due to college exams and graduation. Putting the mod on the Steam Workshop is a very low priority for me, and I haven't played Bannerlord for a long time besides maintaining the mod.

**Comment by shadowhen** [comment]
I have considered publishing EquipBestItem to the Steam Workshop, but I don't have a lot of free time due to college exams. Putting the mod on the Steam Workshop is a very low priority for me, and I haven't played Bannerlord for a long time besides maintaining the mod.
